import { Inter } from "next/font/google";
import "./styles/site.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // font weights
  variable: "--font-inter", // my CSS variable
});

export const metadata = {
  title: 'Landing-Page',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-inter">
        {children}
        </body>
    </html>
  )
}
